# Generated by Django 3.2.9 on 2021-12-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_date_time', models.DateTimeField()),
                ('meeting_link', models.URLField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-meet_date_time', '-created_on'),
            },
        ),
        migrations.CreateModel(
            name='Meeting_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_date_time', models.DateTimeField()),
            ],
        ),
    ]
